### ISSUE TITLE
KarmanVortex.py run fail

### ISSUE THREAD

**Issue by Sehmimul** [Sehmimul/AMATH-361-project#5]
Got following error:

`/opt/homebrew/lib/python3.11/site-packages/pylbm/generator/ast.py:136: SymPyDeprecationWarning: 

The sympy.core.compatibility submodule is deprecated.

This module was only ever intended for internal use. Some of the functions
that were in this module are available from the top-level SymPy namespace,
i.e.,

    from sympy import ordered, default_sort_key

The remaining were only intended for internal SymPy use and should not be used
by user code.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-sympy-core-compatibility
for details.

This has been deprecated since SymPy version 1.10. It
will be removed in a future version of SymPy.

  from sympy.core.compatibility import is_sequence
{'num_frames': 10, 'reynolds_no': 5000000, 'final_time': 1000}
Reynolds number:  5.000e+06
Bulk viscosity :  1.000e-03
Shear viscosity:  1.000e-09
relaxation parameters: [0.0, 0.0, 0.0, 1.4450867052023122, 1.4450867052023122, 1.9999992320002948, 1.9999992320002948, 1.9999992320002948, 1.9999992320002948]
Traceback (most recent call last):
  File "/Users/sehmimul/Desktop/AMATH-361-project/AMATH-361-project/modules/KarmanVortex.py", line 90, in <module>
    'elements': [pylbm.Circle([.3, 0.5*(ymin+ymax)+dx], rayon, label=1)],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pylbm/elements/circle.py", line 82, in __init__
    log.info(self.__str__())
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pylbm/elements/circle.py", line 156, in __str__
    from ..jinja_env import env
  File "/opt/homebrew/lib/python3.11/site-packages/pylbm/jinja_env.py", line 1, in <module>
    from jinja2 import Environment, PackageLoader, select_autoescape
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/homebrew/lib/python3.11/site-packages/markupsafe/__init__.py)`

**Comment by Sehmimul** [comment]
Issue has been resolved:
1. Use `markupsafe=1.1.1` instead of latest version.
2. In `iload1 = np.zeros(self.istore.shape, dtype=np.int)` (line 428) and `iload2 = np.zeros(self.istore.shape, dtype=np.int)` (line 429) of `boundary.py` in `pylbm source code` change `inp.nt` to `np.int32`.
